version: "3.8"

services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
