version: "3.8"

services:
  backend:
    build: ./backend
    container_name: rag-backend
    # No ports exposed to host - internal communication only
    environment:
      - FLASK_ENV=production
    ports:
      - 5000:5000
      
  frontend:
    build: ./frontend
    container_name: rag-frontend
    # No ports exposed to host - internal communication only
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://127.0.0.1:5000  # Use service name for internal communication
    ports:
      - 5173:5173